# Generated by Django 3.1.5 on 2021-03-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_CUSTOMER_PANEL', '0003_customer_customer_feedback_order_details_product_cart_product_review_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
