# Generated by Django 3.1.7 on 2021-04-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_CUSTOMER_PANEL', '0005_auto_20210326_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='order_id',
            field=models.CharField(default='this is null val', max_length=16),
            preserve_default=False,
        ),
    ]
