# Generated by Django 3.1.7 on 2021-04-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_CUSTOMER_PANEL', '0006_order_details_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.CharField(max_length=20),
        ),
    ]
