# Generated by Django 3.1.4 on 2021-04-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_CUSTOMER_PANEL', '0007_auto_20210402_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_feedback',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='retailer_id',
        ),
        migrations.RemoveField(
            model_name='product_cart',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='product_cart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product_review',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='product_review',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='customer_FeedBack',
        ),
        migrations.DeleteModel(
            name='order_details',
        ),
        migrations.DeleteModel(
            name='product_cart',
        ),
        migrations.DeleteModel(
            name='product_review',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
