# Generated by Django 3.1.2 on 2021-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_CUSTOMER_PANEL', '0012_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order_details',
            name='payment_mode',
            field=models.CharField(default='card', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_details',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
