# Generated by Django 3.1.2 on 2021-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_CUSTOMER_PANEL', '0014_remove_order_details_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_product_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
