# Generated by Django 3.1.2 on 2021-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_CUSTOMER_PANEL', '0015_transaction_order_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cart',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
