# Generated by Django 3.1.7 on 2021-05-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_CUSTOMER_PANEL', '0019_auto_20210505_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_product_list',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
