# Generated by Django 3.1.7 on 2021-03-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_ADMIN_PANEL', '0003_auto_20210310_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop_details',
        ),
    ]
