# Generated by Django 3.1.7 on 2021-03-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_ADMIN_PANEL', '0004_delete_shop_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_type', models.CharField(max_length=200)),
                ('shop_country', models.CharField(max_length=30)),
                ('shop_state', models.CharField(max_length=50)),
                ('shop_city', models.CharField(max_length=50)),
                ('shop_pincode', models.IntegerField(blank=True, max_length=10, null=True)),
                ('shop_address', models.CharField(max_length=100)),
                ('view', models.BooleanField(default=False)),
                ('owner_id_proof', models.FileField(upload_to='images/')),
                ('elc_bill', models.FileField(upload_to='images/')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIKIPI_ADMIN_PANEL.retailer')),
            ],
        ),
    ]
