# Generated by Django 3.1.7 on 2021-03-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_ADMIN_PANEL', '0005_shop_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='phnumber',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
