# Generated by Django 3.1.4 on 2021-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_ADMIN_PANEL', '0007_auto_20210313_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='phnumber',
            field=models.IntegerField(blank=True, default=123456, max_length=10),
            preserve_default=False,
        ),
    ]
