# Generated by Django 3.1.4 on 2021-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_ADMIN_PANEL', '0008_auto_20210410_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='phnumber',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
