# Generated by Django 3.1.4 on 2021-04-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_ADMIN_PANEL', '0009_auto_20210410_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop_details',
        ),
    ]
