# Generated by Django 3.1.4 on 2021-04-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_CUSTOMER_PANEL', '0008_auto_20210410_2241'),
        ('VIKIPI_ADMIN_PANEL', '0010_delete_shop_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product_images',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='retailer_feedback',
            name='retailer_id',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='product_images',
        ),
        migrations.DeleteModel(
            name='retailer',
        ),
        migrations.DeleteModel(
            name='retailer_FeedBack',
        ),
    ]
