# Generated by Django 3.1.4 on 2021-04-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VIKIPI_ADMIN_PANEL', '0012_auto_20210410_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VIKIPI_ADMIN_PANEL.shop_details'),
            preserve_default=False,
        ),
    ]
